import type { Trip } from "./trip-schema";

export const SEED_TRIP: Trip = {
  baseOrder: ["moxy", "wagrain", "ramsau", "henriette"],
  regions: {
    moxy: { name: "וינה · הגעה", short: "מוקסי", hex: "#C0851F", hotel: "Moxy (מוקסי)", lat: 48.2169, lng: 16.3989, icon: "ferris" },
    wagrain: { name: "ואגריין", short: "ואגריין", hex: "#1F86AE", hotel: "Alpina Wagrain", lat: 47.3339, lng: 13.2986, icon: "cablecar" },
    ramsau: { name: "רמסאו", short: "רמסאו", hex: "#8B45AD", hotel: "Landhaus Birgbichler", lat: 47.4156, lng: 13.6469, icon: "peak" },
    henriette: { name: "וינה · סיום", short: "וינה", hex: "#4C9438", hotel: "Henriette", lat: 48.2197, lng: 16.3760, icon: "palace" },
  },
  days: [
    { n: 1, d: "14.7", dow: "שלישי", base: "moxy", color: "#C0851F", intensity: 2, icon: "ferris", lat: 48.2169, lng: 16.3989,
      title: "נחיתה ולינה בוינה", acts: ["Prater (פראטר) — גלגל ענק", "כניסה חינם · אטרקציות 5–7€"],
      drive: "הליכה ברגל", cardLabel: "ללא כרטיס", cardClass: "na", food: "כולל ארוחת בוקר · Schweizerhaus",
      rain: "—", tips: "פראטר פתוח עד מאוחר · להביא מזומן", overnight: "הלילה: Moxy (וינה)" },
    { n: 2, d: "15.7", dow: "חמישי", base: "wagrain", color: "#1E6FB0", intensity: 4, icon: "cablecar", lat: 48.0573, lng: 13.8512,
      title: "Traunfall + Grünberg + שביל צמרות", acts: ["Traunfall (מפלי טראון) — מפל 200מ׳", "רכבל Grünberg + Baumwipfelpfad", "מגלשה לאורך ההר"],
      drive: "~2 שעות מוינה", cardLabel: "לא בכרטיס", cardClass: "none", food: "Berggasthof בפסגה / גמונדן",
      rain: "לדלג ולעלות ישר לוואגריין", tips: "עצירה יפה בדרך · מתאים מאוד לבני 6–8" },
    { n: 3, d: "16.7", dow: "שישי", base: "wagrain", color: "#2A9FB5", intensity: 5, icon: "coaster", lat: 47.2700, lng: 12.7560,
      title: "Zell am See + Kaprun", acts: ["Maisi Flitzer (מאיזי פליצר)", "Sigmund Thun Klamm (זיגמונד תון קלאם)", "שחייה באגם צל"],
      drive: "40 דק׳ · 15 דק׳ בין אטרקציות", cardLabel: "לא בכרטיס", cardClass: "none", food: "Maisi Alm (תפריט ילדים)",
      rain: "Tauern Spa Zell am See-Kaprun", tips: "יום עשיר — אקסטרים + טבע + רגיעה" },
    { n: 4, d: "17.7", dow: "שבת", star: true, base: "wagrain", color: "#2FA39C", intensity: 3, icon: "gem", lat: 47.6670, lng: 13.0970,
      title: "Salzwelten Hallein + Bad Dürrnberg", acts: ["מכרה מלח עתיק 2,600 שנה", "2 מגלשות כורים + סירה תת-קרקעית", "SALINA כפר קלטי"],
      drive: "50 דק׳ (A10 דרומה)", cardLabel: "הנחה בכרטיס", cardClass: "discount", food: "Salzblick Restaurant",
      rain: "רוב מקורה", tips: "חובה הזמנה salzwelten.at · 10°C — קחו ז׳קטים" },
    { n: 5, d: "18.7", dow: "ראשון", base: "wagrain", color: "#3E7CC4", intensity: 3, icon: "castle", lat: 47.4800, lng: 13.1870,
      title: "Burg Hohenwerfen (מצודת הוהנוורפן)", acts: ["מופע ציפורי דורסים", "ירי חצים + סיור אבירים", "רכבת זחל למצודה"],
      drive: "25 דקות", cardLabel: "הנחה בכרטיס", cardClass: "discount", food: "מסעדה במצודה / וורפן",
      rain: "רוב מקורה", tips: "תצוגת בזים 11:15 ו-14:15 — חובה! · אחה״צ פנוי" },
    { n: 6, d: "19.7", dow: "שני", base: "wagrain", color: "#5560C0", intensity: 4, icon: "palace", lat: 47.7620, lng: 13.0600,
      title: "Hellbrunn Palace + Salzburg", acts: ["Wasserspiele (מזרקות הפתעה)", "Mirabell Gardens · Mozartplatz", "Festung Hohensalzburg"],
      drive: "55 דקות", cardLabel: "הנחה בכרטיס", cardClass: "discount", food: "Augustiner Bräu / Cafe Tomaselli",
      rain: "DomQuartier Salzburg", tips: "מזרקות ההפתעה — יירטבו! בגדים להחלפה" },
    { n: 7, d: "20.7", dow: "שלישי", base: "wagrain", color: "#1F9BC4", intensity: 2, icon: "spa", lat: 47.1690, lng: 13.1030,
      title: "Alpentherme Gastein (אלפנתרמה גשטיין)", acts: ["Family World — מגלשות + lazy river", "אגמי שחייה תרמיים", "Alpe Adria Dome"],
      drive: "50 דקות", cardLabel: "אזור נפרד", cardClass: "none", food: "מסעדה באתר",
      rain: "מושלם — כולו פתוח בכל מזג", tips: "יום מנוחה ופינוק · ילד עד 6 חינם" },
    { n: 8, d: "21.7", dow: "רביעי", base: "ramsau", color: "#6A4FB0", intensity: 3, icon: "coaster", lat: 47.4130, lng: 13.6590,
      title: "מעבר + Rittisberg Adventure Park", acts: ["Coaster + Flyline", "פארק חבלים בעצים"],
      drive: "5 דקות", cardLabel: "חינם בכרטיס", cardClass: "free", food: "מסעדה ברמסאו / פיקניק",
      rain: "Badeparadies (באדהפראדיז)", tips: "הכרטיס תקף מ-13:00 · לקבל בקבלה!", overnight: "הלילה: Landhaus Birgbichler (רמסאו)" },
    { n: 9, d: "22.7", dow: "חמישי", base: "ramsau", color: "#8A47B0", intensity: 4, icon: "peak", lat: 47.4750, lng: 13.6110,
      title: "Dachstein Glacier + Silberkarklamm", acts: ["Skywalk ב-2,700מ׳", "Stairway to Nothingness + Ice Palace", "Silberkarklamm — ערוץ"],
      drive: "15 דק׳ לרכבל / 10 לערוץ", cardLabel: "פעם בשבוע בכרטיס", cardClass: "discount", food: "מסעדה בפסגה / Silberkarhütte",
      rain: "Salzwelten Altaussee", tips: "קר 4–8°C · חובה הזמנה derdachstein.at · יציאה 08:30" },
    { n: 10, d: "23.7", dow: "שישי", base: "ramsau", color: "#A84A9E", intensity: 4, icon: "kart", lat: 47.3890, lng: 13.6890,
      title: "Hopsiland Planai + Mountain Gokart", acts: ["מגרש משחקים אלפיני 1,850מ׳", "מסלול גוקארט הר 7 ק״מ"],
      drive: "20 דק׳ (10 זה מזה)", cardLabel: "רכבלים חינם", cardClass: "free", food: "מסעדה בפסגת פלאניי",
      rain: "הופסילנד חלקית מקורה", tips: "יום אקשן! · בן 8 גוקארט לבד · בן 6 כנוסע" },
    { n: 11, d: "24.7", dow: "שבת", star: true, base: "ramsau", color: "#7C53C8", intensity: 2, icon: "cablecar", lat: 47.4340, lng: 13.5120,
      title: "Filzmoos + Hofalmen + רכבל Papageno", acts: ["רכבל ל-Hofalmen", "הליכה שטוחה 30–45 דק׳", "חוף רמסאו / Badeparadies"],
      drive: "40 דקות", cardLabel: "חינם בכרטיס", cardClass: "free", food: "בקתות הר · Kaiserschmarrn",
      rain: "באדהפראדיז + מסעדה", tips: "יום רגוע · נוף פוסטקארד · גמיש" },
    { n: 12, d: "25.7", dow: "ראשון", base: "ramsau", color: "#B0468A", intensity: 2, icon: "lake", lat: 47.3920, lng: 13.5660,
      title: "Spiegelsee (אגם המראה) + חוף רמסאו", acts: ["רכבל רייטראלם + 45 דק׳ הליכה לאגם", "שחייה באגם / בריכה מקורה"],
      drive: "25 דק׳ לרייטראלם / 5 לחוף", cardLabel: "הכל חינם", cardClass: "free", food: "מסעדה בפסגה / רמסאו",
      rain: "ערפל → באדהפראדיז", tips: "בוקר = רוח שקטה = השתקפות מושלמת של הקרחון" },
    { n: 13, d: "26.7", dow: "שני", base: "ramsau", color: "#5848C0", intensity: 5, icon: "coaster", lat: 47.3460, lng: 13.3890,
      title: "יום Flachau: Lucky Flitzer + Hermann Maier", acts: ["Lucky Flitzer (לאקי פליצר) 1,100מ׳", "Hermann Maier: Quad + 3D Archery", "פארק שעשועים"],
      drive: "60 דק׳ לכל כיוון (A10)", cardLabel: "אזור Sportwelt", cardClass: "none", food: "Rodelalm Restaurant",
      rain: "כל האטרקציות עובדות בגשם", tips: "מצוין לבני 6–8 · נסיעה 2ש׳ ביום · 09:00–17:00" },
    { n: 14, d: "27.7", dow: "שלישי", star: true, outlier: true, base: "ramsau", color: "#C24E78", intensity: 4, icon: "museum", lat: 48.3100, lng: 14.2840,
      title: "יום מעבר · Ars Electronica (לינץ)", acts: ["Kids Research Lab — 11 תחנות", "Deep Space 8K", "תערוכות אינטראקטיביות"],
      drive: "90 דק׳ ללינץ + 2:30ש׳ לוינה", cardLabel: "לא בכרטיס", cardClass: "none", food: "קפיטריה / Jindrak (לינצר טורטה)",
      rain: "מקורה לחלוטין — אידיאלי לגשם", tips: "בן 6 נכנס חינם · יציאה 10:00 · הגעה הנרייטה 17:00", overnight: "הלילה: עוברים ל-Henriette (וינה)" },
    { n: 15, d: "28.7", dow: "רביעי", base: "henriette", color: "#4E9A3E", intensity: 4, icon: "zoo", lat: 48.1850, lng: 16.3120,
      title: "Schönbrunn + Zoo + Prater", acts: ["ארמון שונברון + מוזיאון הילדים + מבוך", "גן החיות העתיק בעולם — פנדות", "ערב: פראטר"],
      drive: "25 דק׳ ברכב / 30 U4", cardLabel: "אין כרטיס", cardClass: "none", food: "Cafe Residenz / Schweizerhaus",
      rain: "ארמון מקורה + בתי זכוכית", tips: "חובה הזמנה schoenbrunn.at · מבוך מצוין" },
    { n: 16, d: "29.7", dow: "חמישי", base: "henriette", color: "#6FA82A", intensity: 3, icon: "church", lat: 48.2080, lng: 16.3730,
      title: "מרכז העיר ההיסטורי + Haus des Meeres", acts: ["קתדרלת סנט שטפן + עיר עתיקה", "קפה ויני (זאכר / דמל)", "Haus des Meeres — אקווריום + גג 360°"],
      drive: "הליכה / מטרו", cardLabel: "אין כרטיס", cardClass: "none", food: "Café Sacher · Demel · Plachutta",
      rain: "מוזיאון הטבע / Mozarthaus / ZOOM", tips: "יום בלי רכב — לחסוך מחניה" },
    { n: 17, d: "30.7", dow: "שישי", outlier: true, base: "henriette", color: "#2F9E6E", intensity: 1, icon: "plane", lat: 48.1100, lng: 16.5700,
      title: "יום עזיבה · טיסה הביתה", acts: ["ארוחת בוקר אורגנית במלון", "אם יש זמן — הליכה אחרונה בפראטר"],
      drive: "35 דק׳ לנמל", cardLabel: "ללא כרטיס", cardClass: "na", food: "ארוחת בוקר במלון",
      rain: "—", tips: "צ׳ק-אאוט 07:00 · הגעה לנמל 2–3ש׳ לפני (המראה 10:35)" },
  ],
};
