import type { TripInput } from "./trip-schema";

export const NEVELOT_TRIP: TripInput = {
  baseOrder: ["grubhof", "zugspitz", "solden", "mondsee", "vienna"],
  regions: {
    grubhof: {
      name: "לופר · Grubhof",
      short: "לופר",
      hex: "#4FA38A",
      hotel: "Camping Grubhof",
      town: "לופר",
      lat: 47.574,
      lng: 12.706,
      icon: "peak",
      attractions: [
        { name: "רכבל Loferer Alm", desc: "תצפיות מדהימות על האלפים מתחנת הפסגה." },
        { name: "מסלולי הליכה בעמק Saalach", desc: "טיולים רגליים בעמק הירוק. האזור כשעה נסיעה מצלזבורג העיר.", legMin: 10 },
        { name: "קיאקים / Rafting בנהר", desc: "פעילות מים בנהר ה-Saalach.", legMin: 10 },
        { name: "Seisenbergklamm (נקיק)", desc: "קניון יפה במיוחד עם גשרים ומסלול הליכה.", legMin: 15 },
      ],
    },
    zugspitz: {
      name: "ארוואלד · Zugspitz",
      short: "ארוואלד",
      hex: "#5E8AA8",
      hotel: "Zugspitz Resort Camping",
      town: "ארוואלד",
      lat: 47.426,
      lng: 10.942,
      icon: "cablecar",
      attractions: [
        { name: "רכבל Zugspitze (פסגה 2962 מ׳)", desc: "רכבל לפסגה הגבוהה של גרמניה." },
        { name: "אגם Eibsee", desc: "אגם טורקיז למרגלות הצוגשפיצה — מהיפים באלפים.", legMin: 25 },
        { name: "Seebensee hike", desc: "טיול קלאסי לאגם הררי, ~4–5 שעות הליכה.", legMin: 20 },
        { name: "Fernpass scenic road", desc: "כביש נופי דרך מעבר ההר ההיסטורי.", legMin: 10 },
        { name: "מסלולי MTB", desc: "מסלולי אופני הרים סביב Ehrwald.", legMin: 5 },
      ],
    },
    solden: {
      name: "זלדן · Ötztal",
      short: "זלדן",
      hex: "#2E89B0",
      hotel: "Camping Sölden",
      town: "זלדן",
      lat: 46.968,
      lng: 11.007,
      icon: "cablecar",
      attractions: [
        { name: "Gaislachkogelbahn", desc: "רכבל ל-3,040 מ׳ עם מרכז 007 Elements בפסגה." },
        { name: "Bike Republic Sölden", desc: "פארק אופני הרים מהמובילים בעולם.", legMin: 5 },
        { name: "Ötztal Glacier Road", desc: "כביש קרחון הררי — נהיגה מטורפת לשיא 2,829 מ׳.", legMin: 15 },
        { name: "Aqua Dome", desc: "ספא תרמי גדול ב-Längenfeld.", legMin: 25 },
        { name: "Top Mountain Motorcycle Museum", desc: "מוזיאון אופנועים בגובה 2,175 מ׳ על כביש הקרחון.", legMin: 40 },
      ],
    },
    mondsee: {
      name: "מונדזee · MondSeeLand",
      short: "מונדזה",
      hex: "#3B9E8C",
      hotel: "Camp MondSeeLand",
      town: "מונדזה",
      lat: 47.858,
      lng: 13.351,
      icon: "lake",
      attractions: [
        { name: "שחייה וספורט מים באגם", desc: "אגם Mondsee — שחייה ופעילויות מים ישירות מהקמפינג." },
        { name: "Paddle / SUP", desc: "השכרת SUP על המתקנים בקמפינג.", legMin: 0 },
        { name: "עיירת Mondsee", desc: "עיירה ציורית עם הכנסייה מ-The Sound of Music. כ-30 דק׳ נסיעה מצלזבורג.", legMin: 5 },
        { name: "כביש נופי סביב האגמים", desc: "מסלול נסיעה דרך אגמי Salzkammergut.", legMin: 10 },
      ],
    },
    vienna: {
      name: "וינה · סיום",
      short: "וינה",
      hex: "#B07A2A",
      hotel: "דירה במרכז וינה",
      town: "וינה",
      lat: 48.208,
      lng: 16.372,
      icon: "palace",
      attractions: [
        { name: "Hofburg Palace", desc: "ארמון הקיסרים ההיסטורי במרכז וינה." },
        { name: "Figlmüller", desc: "מסעדת השניצל המפורסמת בעיר.", legMin: 5 },
        { name: "Brewing Company 1516", desc: "פאב מבשלה בלב העיר.", legMin: 10 },
        { name: "Café Central", desc: "בית קפה ויאני קלאסי. הדירה ~חצי שעה באובר משדה התעופה.", legMin: 5 },
      ],
    },
  },
  days: [
    {
      n: 1,
      d: "11.6",
      dow: "חמישי",
      base: "grubhof",
      color: "#4FA38A",
      intensity: 3,
      icon: "car",
      lat: 47.574,
      lng: 12.706,
      title: "וינה → Grubhof + Seisenbergklamm",
      acts: [
        "נסיעה מוינה ללופר",
        "Seisenbergklamm — ערוץ מים מרהיב",
        "Loferer Alm — רכבל ומרעות אלפיים",
      ],
      drive: "~300 ק\"מ · 3:15–3:30",
      cardLabel: "",
      cardClass: "na",
      food: "מטבח על המתקנים בקמפינג Grubhof",
      rain: "להאריך נסיעה ולוותר על הקלאם",
      tips: "צ׳ק-אין בקמפינג · קמפינג מודרני על גדת נחל",
      overnight: "הלילה: Camping Grubhof (לופר)",
    },
    {
      n: 2,
      d: "12.6",
      dow: "שישי",
      base: "zugspitz",
      color: "#5E8AA8",
      intensity: 4,
      icon: "car",
      lat: 47.426,
      lng: 10.942,
      title: "Grubhof → Zugspitz Resort + Eibsee",
      acts: [
        "מעבר ל-Ehrwald/Zugspitz",
        "Eibsee — אגם טורקיז למרגלות הצוגשפיצה",
        "טיול קצר סביב האגם",
      ],
      drive: "~150 ק\"מ · 1:45–2:00",
      cardLabel: "",
      cardClass: "na",
      food: "מסעדת הקמפינג · בקתות סביב Eibsee",
      rain: "להישאר בקמפינג · ספא ופאב על המתקנים",
      tips: "Zugspitz Resort עם בריכה, סאונה ופאב",
      overnight: "הלילה: Zugspitz Resort Camping (ארוואלד)",
    },
    {
      n: 3,
      d: "13.6",
      dow: "שבת",
      star: true,
      base: "zugspitz",
      color: "#5E8AA8",
      intensity: 5,
      icon: "peak",
      lat: 47.421,
      lng: 10.985,
      title: "Zugspitze 2962מ׳ + Seebensee",
      acts: [
        "רכבל לפסגת Zugspitze (2962מ׳)",
        "מצפה גבול אוסטריה–גרמניה",
        "מסלול הליכה Seebensee",
      ],
      drive: "10–20 דק׳ לרכבל",
      cardLabel: "",
      cardClass: "na",
      food: "מסעדת פסגה · קפה Seebenalm במסלול",
      rain: "להישאר ברכבל בלבד · לוותר על Seebensee",
      tips: "קר בפסגה — שכבות · Seebensee 4–5ש׳ רגליים",
    },
    {
      n: 4,
      d: "14.6",
      dow: "ראשון",
      base: "solden",
      color: "#2E89B0",
      intensity: 3,
      icon: "car",
      lat: 46.968,
      lng: 11.007,
      title: "Zugspitz → Sölden + Ötztal Glacier Road",
      acts: [
        "מעבר לעמק האטצטל",
        "Ötztal Glacier Road — כביש הקרחון",
        "Top Mountain Motorcycle Museum",
      ],
      drive: "~115 ק\"מ · 1:30–1:45",
      cardLabel: "",
      cardClass: "na",
      food: "מסעדה במוזיאון האופנועים · קמפינג בערב",
      rain: "המוזיאון מקורה — מושלם לגשם",
      tips: "כביש הקרחון — שיא 2829מ׳ · אגרה ברכב",
      overnight: "הלילה: Camping Sölden",
    },
    {
      n: 5,
      d: "15.6",
      dow: "שני",
      base: "solden",
      color: "#2E89B0",
      intensity: 5,
      icon: "cablecar",
      lat: 46.968,
      lng: 11.007,
      title: "Gaislachkogel + Bike Republic + Aqua Dome",
      acts: [
        "Gaislachkogelbahn — רכבל ל-3040מ׳ (007 Elements)",
        "Bike Republic Sölden — אופני הרים",
        "Aqua Dome — ספא תרמי לסיום היום",
      ],
      drive: "5–15 דק׳ בין אטרקציות",
      cardLabel: "",
      cardClass: "na",
      food: "ice Q בפסגה · מסעדה ב-Aqua Dome",
      rain: "ישר ל-Aqua Dome — כולו מקורה",
      tips: "להזמין Aqua Dome מראש · בגד ים + מגבת",
    },
    {
      n: 6,
      d: "16.6",
      dow: "שלישי",
      base: "mondsee",
      color: "#3B9E8C",
      intensity: 3,
      icon: "lake",
      lat: 47.858,
      lng: 13.351,
      title: "Sölden → MondSeeLand + SUP באגם",
      acts: [
        "נסיעה צפונה לעמק האגמים",
        "SUP / שחייה באגם Mondsee",
        "טיול ערב סביב האגם",
      ],
      drive: "~270 ק\"מ · 3:00–3:15",
      cardLabel: "",
      cardClass: "na",
      food: "מסעדת הקמפינג על האגם · דג מקומי",
      rain: "להישאר בקמפינג · סאונה ומקלחות",
      tips: "השכרת SUP על המתקנים · אגם חמים יחסית",
      overnight: "הלילה: Camp MondSeeLand",
    },
    {
      n: 7,
      d: "17.6",
      dow: "רביעי",
      outlier: true,
      base: "vienna",
      color: "#B07A2A",
      intensity: 3,
      icon: "palace",
      lat: 48.208,
      lng: 16.372,
      title: "Mondsee → וינה · Hofburg + ערב סיום",
      acts: [
        "נסיעה חזרה לוינה",
        "Hofburg — ארמון הקיסרים",
        "ארוחת סיום: Figlmüller · Café Central",
      ],
      drive: "~270 ק\"מ · 2:45–3:00",
      cardLabel: "",
      cardClass: "na",
      food: "Figlmüller (שניצל) · Café Central",
      rain: "וינה אורבנית — לא בעיה",
      tips: "צ׳ק-אין בדירה במרכז · ערב חופשי בעיר",
    },
  ],
};
